# Generated by Django 3.1.3 on 2021-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=650)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('genre', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=35)),
                ('year', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
